# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night-blue # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://hjtan.xyz
baseurl : /
title   : 愚思
description: 故事和技术


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  name      : HongjieTan
  avatar    : https://s1.ax1x.com/2020/06/26/NrmSOg.jpg
  bio       : A student studying embedded.
  email     : HongjieTan@outlook.com
  zhihu     : hongjietan
  linkedin  : 宏劼-谭-66a1a81ab
  github    : HongjieTan


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: HongjieTan/hongjietan.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0

## TOC
toc:
  selectors: "h1,h2,h3,h4"

## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: true

## Mermaid
mermaid: true

## Chart
chart:  true

## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num

## => Sharing
##############################
sharing: 
  provider: addthis # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: ra-5ef1861cce3ad741 # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: valine

  valine:
    app_id  : wMhjwFPCwjH9NaXos5wojqjs-gzGzoHsz
    app_key : opllhhdFu2OBEP1cnV9YXr2N
    placeholder : 说点什么吧^_^ 
    meta : 名字,邮箱,网址


## => Pageview
##############################
pageview:
  provider: leancloud

  ## Leancloud
  leancloud:
    app_id    : wMhjwFPCwjH9NaXos5wojqjs-gzGzoHsz
    app_key   : opllhhdFu2OBEP1cnV9YXr2N
    app_class : leancloud


## => Analytics
##############################
analytics:
  provider: google

  ## Google Analytics
  google:
    tracking_id : UA-170181857-1
    anonymize_ip: true


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001